@startuml UseCase Robot VC
left to right direction
' skinparam linetype ortho

:Пользователь: --> (Подключить)
:Пользователь: --> (Состояние пылесоса)
:Пользователь: --> (Запустить уборку)
:Пользователь: --> (Обслуживание)
:Пользователь: --> (Настройка)

(Подключить) --> (Считать QR-код)

(Состояние пылесоса) --> (Уровень заряда АКБ)
(Состояние пылесоса) --> (Заполнение контейнера)
(Состояние пылесоса) --> (Ресурс сменных частей)

(Запустить уборку) --> (Сухая)
(Запустить уборку) --> (Влажная)
(Запустить уборку) --> (Комбинированная)

(Сухая) --> (Прервать/Продолжить)
(Влажная) --> (Прервать/Продолжить)
(Комбинированная) --> (Прервать/Продолжить)

(Прервать/Продолжить) --> (Отправить на базу)

(Обслуживание) --> (Очистка контейнера)
(Обслуживание) --> (Замена/очистка фильтра)
(Обслуживание) --> (Замена/очистка щёток)

(Настройка) --> (Расписание)
(Расписание) --> (Настроить время)
(Расписание) --> (Редактировать)
(Настройка) --> (Карта)
(Карта) --> (Первичное составление)
(Карта) --> (Редактировать карту)
(Настройка) --> (Обновить ПО)
(Настройка) --> (Добавить пользователя)

:Пылесос: --> (Поиск сети)
:Пылесос: --> (Обновление)
:Пылесос: --> (Составление карты)

@enduml