@startuml UseCaseClinic
left to right direction
' skinparam linetype ortho

:Пациент: --> (Записаться)
(Записаться) --> (Первичный приём)
(Записаться) --> (Получить справку)
(Записаться) .> (Сдать анализы)
(Записаться) .> (Получить процедуру)

(Первичный приём) --> (Получить процедуру)
(Первичный приём) --> (Сдать анализы)
(Первичный приём) --> (Получить справку)
(Первичный приём) --> (Получить больничный)
(Первичный приём) --> (Получить рецепт)
(Первичный приём) --> (Получить направление)

(Получить направление) .> (Записаться)

(Сдать анализы) --> (Получить результаты)
(Получить процедуру) --> (Получить результаты)

(Получить рецепт) --> (Поставить печать/визу)
(Получить результаты) --> (Поставить печать/визу)
(Получить больничный) --> (Поставить печать/визу)

:Медработник: --> (Открыть расписание)
(Открыть расписание) --> (Принять пациента)
(Принять пациента) --> (Открыть медкарту)

(Открыть медкарту) --> (Записать диагноз)
(Открыть медкарту) --> (Открыть направление)
(Открыть медкарту) --> (Выписать рецепт)
(Открыть медкарту) --> (Открыть больничный)

(Записать диагноз) --> (Закрыть медкарту)
(Открыть направление) --> (Закрыть медкарту)
(Выписать рецепт) --> (Закрыть медкарту)
(Открыть больничный) --> (Закрыть медкарту)

@enduml